---
title: "Comparison of continuous albuterol usage and patient outcomes prior to shortage vs. after shortage"
author: "Megan Moore, Karen Williams"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: github_document
---

## Objective

To evaluate and compare the usage of continuous albuterol in the pediatric asthma population prior to shortage (usual use per pediatric asthma pathway) vs. after shortage (per shortage plan) 

## Methods

### MUE Criteria

* Data collection period: September 22, 2017-October 19, 2017 compared to September 22, 2016-October 19, 2016
* Patients receiving continuous albuterol, continuous albuterol + MDI, albuterol MDI alone at initiation and at any point
* Indication: Asthma

### Data Collection

* Demographics
    - Age (years)
    - Sex (M/F)
    - Weight (kilograms)
    - Race
* Albuterol dose:
    - Starting dose 
        + MDI or Cont or both 
        + MDI
            * Puffs 
            * Interval 
            * Mg/kg/hr
        + Nebs 
            * Mg 
            * Interval 
        + Continuous 
            * Mg/hr 
            * Mg/kg/hr
        + MDI and Continuous albuterol 
            * Cumulative mg/kg/hr
    - Maintenance 
        + Continuous albuterol 
            * 5 / 10 / 20 mg/hr
            * Duration (hours)
            * Mg/kg/hr
        + MDI and Continuous albuterol 
            * Duration (hours)
            * Cumulative mg/kg/day
        + Number of dose changes during entire stay
            * Increase dose at any point: yes or no 
            * Number of increased dose
        + Total duration of continuous albuterol 
    - MDI
        + 6 or 10 puffs
        + Q2H, Q3H, Q4H, Other
            * Duration
            * Mg/kg/hr
        + Other number of puff
            * Interval 
            * Duration 
            * Mg/kg/hr
    - Total dose of continuous albuterol neb while on continuous albuterol only
        + Total mg 
        + mg/kg
        + Number of continuous albuterol dose changes (#)
        + Duration (days)
    - MDI + Continuous albuterol 
        + Total dose 
            * mg 
            * mg/kg
        + Duration (days)
    - Total dose of albuterol MDI after Continuous albuterol 
        + Total mg 
        + mg/kg
        + Duration of albuterol MDI Q2h / Q3h / Q4h (days)
    - Any increase in albuterol dosing (Y / N) 
        + Q3h to Q2h 
        + Q4h to Q3h
        + Duration of increased dose(days)
* Total duration of all albuterol until Q4H? (days)
* Steroids (including prescription for post-discharge)
    - Total dose of methylprednisolone/prednisone/prednisolone? 
        + Mg/day
        + Mg/kg/day 
        + Mg/kg/total
        + Duration of methylprednisolone/prednisone/prednisolone? (days) 
    - Total dose of dexamethasone? 
        + Mg/day
        + Mg/kg/day 
        + Mg/kg/total
        + Duration of dexamethasone? (days) 
* Number of IV magnesium doses? (#)
    - Magnesium dose given for entire LOS? 
        + Total number of dose/day 
        + Max number of doses per day
        + Mg/dose
        + Mg/kg/dose 
        + Mg/kg/day
        + Mg/kg/total
* Allergies? (Y/N)
    - If Yes: Treated? (Y / N)
    - Specify treatment:
        + LTRAs
        + Antihistamines
        + Steroid nasal sprays
    - Time of first dose from admission
* Adverse effects:
    - Hypotension within 12 hrs after IV magnesium? ( Y / N)

## Outcomes

* Hospital length of stay? (days)
* Increase in level of care (transfer from gen peds to IMU during admission due to asthma)? (Y / N)
* Increase in level of care (transfer to PICU during admission due to asthma)? (Y / N)
* Increased respiratory support at any point (nasal cannula, highflow nasal cannula, CPAP, Bipap, or mechanical ventilation)? (Y / N)
    - Which one(s)? (specify)
    - Duration? (days)

#### Definitions
* Hypotension: Hypotension is a systolic blood pressure <5th percentile of normal for age, namely:
    - <60 mm Hg in term neonates (0 to 28 days)
    - <70 mm Hg in infants (1 to 12 months)
    - <70 mm Hg + (2 x age in years) in children 1 to 10 years
    - <90 mm Hg in children ≥10 years of age
